import "dotenv/config";
import bcrypt from "bcryptjs";
import { eq } from "drizzle-orm";
import { db } from "./client.ts";
import { staff, products, productVariants, productImages, collections, collectionProducts, drops, dropProducts, deliveryZones } from "./schema.ts";
import { PRODUCTS, COLLECTIONS } from "../data/set-apart.ts";

async function seedStore(){
 const productIds:number[]=[];
 for(let i=0;i<PRODUCTS.length;i++){const p=PRODUCTS[i];const slug=p.name.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/(^-|-$)/g,"");const existing=await db.query.products.findFirst({where:eq(products.slug,slug)});let id=existing?.id;if(id)await db.update(products).set({name:p.name,description:p.description,price:p.price.toFixed(2),category:p.collection.toLowerCase(),featured:i<4,bestseller:i===0||i===2,active:true,updatedAt:new Date()}).where(eq(products.id,id));else{id=(await db.insert(products).values({name:p.name,slug,description:p.description,price:p.price.toFixed(2),category:p.collection.toLowerCase(),featured:i<4,bestseller:i===0||i===2,active:true}).returning({id:products.id}))[0].id}productIds.push(id);await db.delete(productImages).where(eq(productImages.productId,id));await db.insert(productImages).values({productId:id,url:p.image,alt:p.name,sortOrder:0});await db.delete(productVariants).where(eq(productVariants.productId,id));await db.insert(productVariants).values(p.sizes.map((size,j)=>({productId:id!,sku:`SAP-${String(id).padStart(3,"0")}-${p.color.slice(0,2).toUpperCase()}-${size}`,size,color:p.color,stock:10,active:true,price:p.price.toFixed(2)})));}
 for(let i=0;i<COLLECTIONS.length;i++){const c=COLLECTIONS[i];const existing=await db.query.collections.findFirst({where:eq(collections.slug,c.slug)});let id=existing?.id;if(id)await db.update(collections).set({name:c.name,description:c.description,active:true,sortOrder:i,updatedAt:new Date()}).where(eq(collections.id,id));else{id=(await db.insert(collections).values({name:c.name,slug:c.slug,description:c.description,active:true,sortOrder:i}).returning({id:collections.id}))[0].id}await db.delete(collectionProducts).where(eq(collectionProducts.collectionId,id));const wanted=PRODUCTS.map((p,j)=>p.collection.toLowerCase()===c.name.toLowerCase()?productIds[j]:null).filter((x):x is number=>x!==null);if(wanted.length)await db.insert(collectionProducts).values(wanted.map(productId=>({collectionId:id!,productId})));}
 console.log(`Seeded ${productIds.length} products and ${COLLECTIONS.length} collections.`);
}
async function seedDrop(){const slug="anime-vol-01";const existing=await db.query.drops.findFirst({where:eq(drops.slug,slug)});let id=existing?.id;if(!id)id=(await db.insert(drops).values({name:"Anime Vol. 01",slug,description:"The first SET APART anime drop.",status:"live"}).returning({id:drops.id}))[0].id;await db.delete(dropProducts).where(eq(dropProducts.dropId,id));const ps=await db.query.products.findMany({where:eq(products.category,"anime")});if(ps.length)await db.insert(dropProducts).values(ps.map(p=>({dropId:id!,productId:p.id})));}
async function seedZones(){if((await db.query.deliveryZones.findMany()).length)return;for(const [i,z] of [{name:"Takoradi",fee:"15.00"},{name:"Sekondi",fee:"15.00"},{name:"Other Ghana",fee:"30.00"}].entries())await db.insert(deliveryZones).values({...z,sortOrder:i});}
async function seedStaff(){for(const [role,email,password,name] of [["admin",process.env.STAFF_ADMIN_EMAIL,process.env.STAFF_ADMIN_PASSWORD,process.env.STAFF_ADMIN_NAME??"SET APART Admin"],["super_admin",process.env.SUPER_ADMIN_EMAIL,process.env.SUPER_ADMIN_PASSWORD,process.env.SUPER_ADMIN_NAME??"SET APART Super Admin"]] as const){if(!email||!password)continue;const existing=await db.query.staff.findFirst({where:eq(staff.email,email)});if(!existing)await db.insert(staff).values({name,email,passwordHash:await bcrypt.hash(password,12),role,active:true});}}
async function main(){console.log("Seeding SET APART…");await seedStore();await seedDrop();await seedZones();await seedStaff();console.log("Done.");}
main().then(()=>process.exit(0)).catch(e=>{console.error(e);process.exit(1)});
