import { createServerFn } from "@tanstack/react-start";
import { eq, desc, and, gte, lte, inArray, sql } from "drizzle-orm";
import crypto from "node:crypto";
import { z } from "zod";
import { db } from "@/db/client";
import { products, productVariants, orders, orderItems, orderStatusHistory, deliveryZones, ORDER_STATUS_FLOW, customers, promotionCodes, promotionUsage } from "@/db/schema";
import { requireStaff } from "./auth";
import { logActivity } from "@/lib/activity-log";

const OPERATIONAL_ROLES=["admin","staff"] as const;
const cartItemSchema=z.object({productId:z.number(),variantId:z.number(),quantity:z.number().int().min(1).max(50),customDesignId:z.number().optional(),specialInstructions:z.string().max(300).optional()});
const createOrderSchema=z.object({customerName:z.string().min(1).max(160),customerPhone:z.string().min(6).max(40),customerEmail:z.string().email().optional().or(z.literal("")),orderType:z.enum(["pickup","delivery"]),deliveryAddress:z.string().max(400).optional(),deliveryNotes:z.string().max(400).optional(),deliveryZoneId:z.number().optional(),promotionCode:z.string().max(40).optional(),items:z.array(cartItemSchema).min(1)});
const token=()=>crypto.randomBytes(24).toString("base64url");

export const createOrder=createServerFn({method:"POST"}).validator(createOrderSchema).handler(async({data})=>{
 if(data.orderType==="delivery"&&!data.deliveryAddress?.trim())throw new Error("Delivery address is required.");
 let deliveryFee=0,deliveryZoneId:null|number=null,deliveryZoneName:null|string=null;
 if(data.orderType==="delivery"){if(!data.deliveryZoneId)throw new Error("Choose a delivery area.");const zne=await db.query.deliveryZones.findFirst({where:eq(deliveryZones.id,data.deliveryZoneId)});if(!zne||!zne.active)throw new Error("That delivery area is unavailable.");deliveryFee=Number(zne.fee);deliveryZoneId=zne.id;deliveryZoneName=zne.name;}
 const ids=[...new Set(data.items.map(x=>x.productId))];const vars=[...new Set(data.items.map(x=>x.variantId))];
 const ps=await db.query.products.findMany({where:and(inArray(products.id,ids),eq(products.active,true))});const vs=await db.query.productVariants.findMany({where:and(inArray(productVariants.id,vars),eq(productVariants.active,true))});
 const pm=new Map(ps.map(x=>[x.id,x])),vm=new Map(vs.map(x=>[x.id,x]));let subtotal=0;
 const lines=[] as any[];
 for(const line of data.items){const p=pm.get(line.productId),v=vm.get(line.variantId);if(!p||!v||v.productId!==p.id)throw new Error("One of the selected products is unavailable.");if(v.stock<line.quantity)throw new Error(`${p.name} (${v.size}/${v.color}) does not have enough stock.`);const price=Number(v.price??p.price),sub=price*line.quantity;subtotal+=sub;lines.push({productId:p.id,productVariantId:v.id,size:v.size,color:v.color,itemName:p.name,variantLabel:`${v.color} / ${v.size}`,unitPrice:price.toFixed(2),quantity:line.quantity,subtotal:sub.toFixed(2),customDesignId:line.customDesignId??null,specialInstructions:line.specialInstructions??null});}
 let customerId:number|null=null;if(data.customerEmail){const existing=await db.query.customers.findFirst({where:eq(customers.email,data.customerEmail.toLowerCase())});if(existing)customerId=existing.id;else{const [c]=await db.insert(customers).values({name:data.customerName,email:data.customerEmail.toLowerCase(),phone:data.customerPhone}).returning({id:customers.id});customerId=c.id;}}
 let discount=0;let promotionId:number|null=null;let promotionCode:string|null=null;
 if(data.promotionCode){const code=data.promotionCode.trim().toUpperCase();const promo=await db.query.promotionCodes.findFirst({where:eq(promotionCodes.code,code)});const now=new Date();if(!promo||!promo.active||(promo.startsAt&&promo.startsAt>now)||(promo.endsAt&&promo.endsAt<now)||(promo.usageLimit!=null&&promo.usedCount>=promo.usageLimit)|| (promo.minimumSubtotal!=null&&subtotal<Number(promo.minimumSubtotal)))throw new Error("That promo code is invalid or no longer available.");discount=promo.type==="percentage"?Math.min(subtotal,subtotal*Number(promo.value)/100):Math.min(subtotal,Number(promo.value));promotionId=promo.id;promotionCode=promo.code;}
 const total=subtotal-discount+deliveryFee;const trackingToken=token();const [o]=await db.insert(orders).values({orderNumber:"PENDING",trackingToken,customerName:data.customerName,customerPhone:data.customerPhone,customerEmail:data.customerEmail||null,customerId,orderType:data.orderType,deliveryAddress:data.orderType==="delivery"?data.deliveryAddress:null,deliveryNotes:data.deliveryNotes||null,deliveryZoneId,deliveryZoneName,subtotal:subtotal.toFixed(2),deliveryFee:deliveryFee.toFixed(2),total:total.toFixed(2),discount:discount.toFixed(2),promotionCode,paymentStatus:"pending",orderStatus:"pending"}).returning({id:orders.id});
 const orderNumber=`SAP-${1000+o.id}`;await db.update(orders).set({orderNumber}).where(eq(orders.id,o.id));await db.insert(orderItems).values(lines.map(x=>({orderId:o.id,...x})));await db.insert(orderStatusHistory).values({orderId:o.id,previousStatus:null,newStatus:"pending",changedByStaffId:null});
 // Reserve inventory immediately; payment failure will not restore it automatically, so a production reconciliation job can handle abandoned orders.
 const reserved:{id:number;quantity:number}[]=[];
 try {
   for(const line of lines) { const result=await db.update(productVariants).set({stock:sql`${productVariants.stock} - ${line.quantity}`,updatedAt:new Date()}).where(and(eq(productVariants.id,line.productVariantId),gte(productVariants.stock,line.quantity))).returning({id:productVariants.id}); if(!result.length) throw new Error("Stock changed while you were checking out. Please try again."); reserved.push({id:line.productVariantId,quantity:line.quantity}); }
 } catch (error) { for(const r of reserved) await db.update(productVariants).set({stock:sql`${productVariants.stock} + ${r.quantity}`,updatedAt:new Date()}).where(eq(productVariants.id,r.id)); throw error; }
 return {orderId:o.id,orderNumber,trackingToken,subtotal,deliveryFee,total};
});

export const getOrderByToken=createServerFn({method:"GET"}).validator(z.object({token:z.string().min(10)})).handler(async({data})=>{const o=await db.query.orders.findFirst({where:eq(orders.trackingToken,data.token),with:{items:true}});if(!o)throw new Error("Order not found.");return {orderNumber:o.orderNumber,orderType:o.orderType,orderStatus:o.orderStatus,paymentStatus:o.paymentStatus,deliveryZoneName:o.deliveryZoneName,subtotal:Number(o.subtotal),deliveryFee:Number(o.deliveryFee),discount:Number(o.discount),total:Number(o.total),createdAt:o.createdAt,items:o.items.map(i=>({name:i.itemName,variantLabel:i.variantLabel,quantity:i.quantity,unitPrice:Number(i.unitPrice),subtotal:Number(i.subtotal),size:i.size,color:i.color}))};});

const listSchema=z.object({orderType:z.enum(["pickup","delivery"]).optional(),status:z.enum(["pending","accepted","preparing","ready","out_for_delivery","completed","cancelled"]).optional(),paymentStatus:z.enum(["pending","paid","failed","refunded"]).optional(),fromDate:z.string().optional(),toDate:z.string().optional()});
export const listOrders=createServerFn({method:"GET"}).validator(listSchema).handler(async({data})=>{await requireStaff({role:OPERATIONAL_ROLES});const c:any[]=[];if(data.orderType)c.push(eq(orders.orderType,data.orderType));if(data.status)c.push(eq(orders.orderStatus,data.status));if(data.paymentStatus)c.push(eq(orders.paymentStatus,data.paymentStatus));if(data.fromDate)c.push(gte(orders.createdAt,new Date(data.fromDate)));if(data.toDate)c.push(lte(orders.createdAt,new Date(data.toDate)));const rows=await db.query.orders.findMany({where:c.length?and(...c):undefined,orderBy:desc(orders.createdAt),with:{items:true},limit:200});return rows.map(o=>({id:o.id,orderNumber:o.orderNumber,customerName:o.customerName,customerPhone:o.customerPhone,orderType:o.orderType,deliveryZoneName:o.deliveryZoneName,orderStatus:o.orderStatus,paymentStatus:o.paymentStatus,total:Number(o.total),itemCount:o.items.reduce((s,i)=>s+i.quantity,0),createdAt:o.createdAt}));});
export const getOrderById=createServerFn({method:"GET"}).validator(z.object({id:z.number()})).handler(async({data})=>{await requireStaff({role:OPERATIONAL_ROLES});const o=await db.query.orders.findFirst({where:eq(orders.id,data.id),with:{items:true,statusHistory:{orderBy:desc(orderStatusHistory.createdAt)},payments:true}});if(!o)throw new Error("Order not found.");return o;});
const statusSchema=z.object({orderId:z.number(),newStatus:z.enum(["pending","accepted","preparing","ready","out_for_delivery","completed","cancelled"])});
function valid(cur:string,next:string){if(next==="cancelled")return cur!=="completed"&&cur!=="cancelled";const a=ORDER_STATUS_FLOW.indexOf(cur as any),b=ORDER_STATUS_FLOW.indexOf(next as any);return a>=0&&b===a+1;}
export const updateOrderStatus=createServerFn({method:"POST"}).validator(statusSchema).handler(async({data})=>{const staff=await requireStaff({role:OPERATIONAL_ROLES});const o=await db.query.orders.findFirst({where:eq(orders.id,data.orderId)});if(!o)throw new Error("Order not found.");if(!valid(o.orderStatus,data.newStatus))throw new Error(`Cannot move order from ${o.orderStatus} to ${data.newStatus}.`);await db.update(orders).set({orderStatus:data.newStatus,updatedAt:new Date()}).where(eq(orders.id,o.id));await db.insert(orderStatusHistory).values({orderId:o.id,previousStatus:o.orderStatus,newStatus:data.newStatus,changedByStaffId:staff.id});await logActivity({staffId:staff.id,staffName:staff.name,staffRole:staff.role,action:`Marked order ${o.orderNumber} as ${data.newStatus}`,entityType:"order",entityId:o.orderNumber});return {success:true};});
export const getDashboardStats=createServerFn({method:"GET"}).handler(async()=>{await requireStaff({role:OPERATIONAL_ROLES});const start=new Date();start.setHours(0,0,0,0);const rows=await db.query.orders.findMany({where:gte(orders.createdAt,start)});const paid=rows.filter(x=>x.paymentStatus==="paid"),sales=paid.reduce((s,x)=>s+Number(x.total),0);return {todayOrders:rows.length,pending:rows.filter(x=>x.orderStatus==="pending").length,accepted:rows.filter(x=>x.orderStatus==="accepted").length,preparing:rows.filter(x=>x.orderStatus==="preparing").length,ready:rows.filter(x=>x.orderStatus==="ready").length,outForDelivery:rows.filter(x=>x.orderStatus==="out_for_delivery").length,completed:rows.filter(x=>x.orderStatus==="completed").length,cancelled:rows.filter(x=>x.orderStatus==="cancelled").length,todaySales:sales,averageOrderValue:paid.length?sales/paid.length:0};});
